[build]
builder = "NIXPACKS"

[deploy]
preDeployCommand = "python manage.py collectstatic --no-input && python manage.py migrate"
startCommand = "gunicorn config.wsgi --bind 0.0.0.0:$PORT --log-file -"
