TEAMS = [
    ("Arizona Cardinals", "Arizona Cardinals"),
    ("Atlanta Falcons", "Atlanta Falcons"),
    ("Baltimore Ravens", "Baltimore Ravens"),
    ("Buffalo Bills", "Buffalo Bills"),
    ("Carolina Panthers", "Carolina Panthers"),
    ("Chicago Bears", "Chicago Bears"),
    ("Cincinnati Bengals", "Cincinnati Bengals"),
    ("Cleveland Browns", "Cleveland Browns"),
    ("Dallas Cowboys", "Dallas Cowboys"),
    ("Denver Broncos", "Denver Broncos"),
    ("Detroit Lions", "Detroit Lions"),
    ("Green Bay Packers", "Green Bay Packers"),
    ("Houston Texans", "Houston Texans"),
    ("Indianapolis Colts", "Indianapolis Colts"),
    ("Jacksonville Jaguars", "Jacksonville Jaguars"),
    ("Kansas City Chiefs", "Kansas City Chiefs"),
    ("Las Vegas Raiders", "Las Vegas Raiders"),
    ("Los Angeles Chargers", "Los Angeles Chargers"),
    ("Los Angeles Rams", "Los Angeles Rams"),
    ("Miami Dolphins", "Miami Dolphins"),
    ("Minnesota Vikings", "Minnesota Vikings"),
    ("New England Patriots", "New England Patriots"),
    ("New Orleans Saints", "New Orleans Saints"),
    ("New York Giants", "New York Giants"),
    ("New York Jets", "New York Jets"),
    ("Philadelphia Eagles", "Philadelphia Eagles"),
    ("Pittsburgh Steelers", "Pittsburgh Steelers"),
    ("San Francisco 49ers", "San Francisco 49ers"),
    ("Seattle Seahawks", "Seattle Seahawks"),
    ("Tampa Bay Buccaneers", "Tampa Bay Buccaneers"),
    ("Tennessee Titans", "Tennessee Titans"),
    ("Washington Commanders", "Washington Commanders"),
]

NFC_TEAMS = TEAMS[:16]
AFC_TEAMS = TEAMS[16:]

TEAM_ABBREV = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KC",
    "Las Vegas Raiders": "LV",
    "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NE",
    "New Orleans Saints": "NO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "San Francisco 49ers": "SF",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN",
    "Washington Commanders": "WAS",
}

ABBREV_TO_TEAM = {v: k for k, v in TEAM_ABBREV.items()}
