# Generated by Django 6.0.6 on 2026-06-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
