# Generated by Django 6.0.6 on 2026-06-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_preseason_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bot_preference',
            field=models.CharField(blank=True, choices=[('underdog', 'Underdog'), ('favorite', 'Favorite')], default='', max_length=10),
        ),
    ]
