# Generated by Django 6.0.6 on 2026-06-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bot_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bot_preference',
        ),
        migrations.AddField(
            model_name='profile',
            name='bot_underdog_pct',
            field=models.IntegerField(default=50),
        ),
    ]
