# Generated by Django 6.0.6 on 2026-08-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_replace_bot_preference_with_underdog_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bot_strategy',
            field=models.CharField(choices=[('random', 'Random (uses underdog %)'), ('gemini', 'Gemini AI picks each game')], default='random', help_text='How this bot decides its picks. Only applies when is_bot is set.', max_length=20),
        ),
    ]
