# Generated by Django 6.0.6 on 2026-08-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bot_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_posts_enabled',
            field=models.BooleanField(default=False, help_text="Publish this member's league-wide emails on the site."),
        ),
    ]
