# Generated by Django 6.1.1 on 2026-09-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_email_posts_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unread_messages',
        ),
    ]
