# Generated by Django 6.0.6 on 2026-06-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='weekly_recap',
            field=models.TextField(blank=True, default=''),
        ),
    ]
