# Generated by Django 6.0.6 on 2026-08-17 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_split_scrape_and_grade_api'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=120)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('inbound', 'Received from a member'), ('site', 'Sent by the site')], default='inbound', max_length=10)),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(max_length=400, unique=True)),
                ('recipient_count', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True, help_text='Uncheck to hide from the site without deleting.')),
                ('author', models.ForeignKey(blank=True, help_text='The member whose address it came from, when one matched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.AddIndex(
            model_name='leagueemail',
            index=models.Index(fields=['-sent_at'], name='main_league_sent_at_d3c91e_idx'),
        ),
    ]
