# Generated by Django 6.0.6 on 2026-08-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_backfill_recaps_into_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_ballot',
            field=models.BooleanField(default=True, help_text='Include the reply-by-email ballot in that mail, so members can send picks by deleting the team they do not want.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_confirmations',
            field=models.BooleanField(default=True, help_text='Reply to emailed picks confirming what was recorded. Off leaves members no way to catch a misread.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_picks_live',
            field=models.BooleanField(default=True, help_text='Mail the league when a week is published.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_recap',
            field=models.BooleanField(default=True, help_text="Mail PutnamBot's recap when a week is scored."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_relay',
            field=models.BooleanField(default=True, help_text="Forward the commissioner's league emails on to every member."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='recap_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
