# Generated by Django 6.0.6 on 2026-08-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sitesettings_email_ballot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=400, unique=True)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
    ]
