# Generated by Django 6.0.6 on 2026-08-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_backfill_processed_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='deferred',
            field=models.BooleanField(default=False),
        ),
    ]
