# Generated by Django 6.0.6 on 2026-08-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_home_team_to_team1_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_advance',
            field=models.BooleanField(default=True, help_text='Roll to the next week once every game is graded.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_first_attempt_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_grade_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_grade_hour',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_grade_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_grade_weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_last_issue',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='auto_retry_window_minutes',
            field=models.IntegerField(default=360, help_text='Keep retrying a bad scrape for this many minutes, then publish anyway.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scrape_days',
            field=models.CharField(blank=True, default='', help_text='Weekdays the league picks games on, 0=Mon…6=Sun. Blank = all days.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='season_last_week',
            field=models.IntegerField(default=22, help_text='Final week of the season. Autopilot stops here.'),
        ),
    ]
