# Generated by Django 6.0.6 on 2026-08-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_carry_day_filter_into_scrape_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_grade_hour',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_grade_minute',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_grade_weekday',
        ),
    ]
