# Generated by Django 6.0.6 on 2026-08-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_sitesettings_auto_grade_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_reminder',
            field=models.BooleanField(default=True, help_text='Nudge anyone whose picks are still incomplete before they lock.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reminder_hours_before_lock',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reminder_sent_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekly_intro',
            field=models.TextField(blank=True, default='', help_text="Optional note from the commissioner, top of this week's email."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_recap',
            field=models.BooleanField(default=True, help_text="Include last week's recap in the picks-are-live email. The recap no longer goes out on its own - one mail a week, not two."),
        ),
    ]
