# Generated by Django 6.0.6 on 2026-08-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_seed_intro_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='intro_prompt',
        ),
    ]
