# Generated by Django 6.1.1 on 2026-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_sitesettings_intro_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='scrape_filter_from_day',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='scrape_filter_to_day',
        ),
        migrations.AddField(
            model_name='seasonrecord',
            name='weekly',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='seasonrecord',
            name='weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Bug',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
